# Generated by Django 5.0 on 2026-04-24 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0002_alter_systemlog_app_label'),
        ('staffs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary subject for this teacher')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_teachers', to='corecode.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_subjects', to='staffs.staff')),
            ],
            options={
                'verbose_name': 'Teacher Subject Qualification',
                'verbose_name_plural': 'Teacher Subject Qualifications',
                'permissions': [('manage_qualifications', 'Can manage teacher subject qualifications')],
                'unique_together': {('teacher', 'subject')},
            },
        ),
        migrations.DeleteModel(
            name='SubjectAssignment',
        ),
    ]
