# Generated by Django 5.0 on 2026-07-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, help_text='Student ID from students app (null for application fees)', max_length=50, null=True),
        ),
    ]
