# Generated by Django 5.0 on 2026-03-30 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(choices=[('tuition', 'Tuition Fee'), ('development', 'Development Levy'), ('sports', 'Sports Fee'), ('library', 'Library Fee'), ('laboratory', 'Laboratory Fee'), ('exam', 'Examination Fee'), ('registration', 'Registration Fee'), ('uniform', 'Uniform Fee'), ('transport', 'Transport Fee'), ('ict', 'ICT Fee'), ('application', 'Application Fee'), ('other', 'Other Fee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fee_type',
            field=models.CharField(choices=[('tuition', 'Tuition Fee'), ('development', 'Development Levy'), ('sports', 'Sports Fee'), ('library', 'Library Fee'), ('laboratory', 'Laboratory Fee'), ('exam', 'Examination Fee'), ('registration', 'Registration Fee'), ('uniform', 'Uniform Fee'), ('transport', 'Transport Fee'), ('ict', 'ICT Fee'), ('application', 'Application Fee'), ('other', 'Other Fee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='student_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Student ID from students app (null for application fees)', null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['fee_type'], name='finance_inv_fee_typ_dcc7b5_idx'),
        ),
    ]
