# Generated by Django 5.0 on 2026-04-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='application_id',
            field=models.IntegerField(blank=True, help_text='ID of the admissions application that created this student', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='application_number',
            field=models.CharField(blank=True, help_text='Application number from admissions app', max_length=20, null=True),
        ),
    ]
