# Generated by Django 5.0 on 2026-04-24 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0002_alter_systemlog_app_label'),
        ('staffs', '0002_teachersubjectqualification_delete_subjectassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_teaching', models.BooleanField(default=True)),
                ('duration_minutes', models.IntegerField(default=40)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
                ('is_break', models.BooleanField(default=False)),
                ('break_duration_minutes', models.IntegerField(default=60)),
            ],
            options={
                'verbose_name': 'Period Type',
                'verbose_name_plural': 'Period Types',
            },
        ),
        migrations.CreateModel(
            name='SchoolDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True)),
                ('name', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('is_friday', models.BooleanField(default=False)),
                ('friday_start_time', models.TimeField(blank=True, null=True)),
                ('friday_end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'School Day',
                'verbose_name_plural': 'School Days',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession')),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.academicterm')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timetables', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetables', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.timetable')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='corecode.studentclass')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'ordering': ['-academic_session', '-academic_term', 'student_class'],
                'permissions': [('publish_timetable', 'Can publish and activate timetables'), ('view_all_timetables', 'Can view all timetables across classes')],
                'unique_together': {('academic_session', 'academic_term', 'student_class', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TimetablePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('display_name', models.CharField(max_length=50)),
                ('is_flexible', models.BooleanField(default=False)),
                ('period_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.periodtype')),
                ('school_days', models.ManyToManyField(related_name='periods', to='timetable.schoolday')),
            ],
            options={
                'verbose_name': 'Timetable Period',
                'verbose_name_plural': 'Timetable Periods',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free_period', models.BooleanField(default=False, help_text='Mark as free/study period')),
                ('room', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_temporary', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.schoolday')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.timetableperiod')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='corecode.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='staffs.staff')),
                ('temporary_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_slots', to='corecode.subject')),
                ('temporary_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_slots', to='staffs.staff')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.timetable')),
            ],
            options={
                'verbose_name': 'Timetable Slot',
                'verbose_name_plural': 'Timetable Slots',
                'ordering': ['day__order', 'period__order'],
            },
        ),
        migrations.CreateModel(
            name='TimetableClashLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.schoolday')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clash_logs', to='timetable.timetable')),
                ('period_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clash_as_period1', to='timetable.timetableperiod')),
                ('period_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clash_as_period2', to='timetable.timetableperiod')),
                ('slot_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clash_as_slot1', to='timetable.timetableslot')),
                ('slot_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clash_as_slot2', to='timetable.timetableslot')),
            ],
            options={
                'verbose_name': 'Timetable Clash Log',
                'verbose_name_plural': 'Timetable Clash Logs',
            },
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['timetable', 'teacher'], name='timetable_t_timetab_ae07fb_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['timetable', 'subject'], name='timetable_t_timetab_1a5b5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('timetable', 'day', 'period')},
        ),
        migrations.AddIndex(
            model_name='timetableclashlog',
            index=models.Index(fields=['timetable', 'resolved_at'], name='timetable_t_timetab_ffd7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableclashlog',
            index=models.Index(fields=['teacher', 'detected_at'], name='timetable_t_teacher_05d7c2_idx'),
        ),
    ]
