# Generated by Django 5.0 on 2026-03-15 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_id', models.IntegerField(db_index=True, help_text='Guardian ID from students app')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('access_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('access_key', models.CharField(default='5c2bd3350f6841dc9b8098ad8f7947df', help_text='Unique key for portal access URL', max_length=64, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('preferred_language', models.CharField(default='en', help_text='Preferred language for communications', max_length=10)),
                ('notification_preferences', models.JSONField(default=dict, help_text='JSON storing notification channel preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='parents.parentprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment_receipt', 'Payment Receipt'), ('payment_reminder', 'Payment Reminder'), ('result_published', 'Results Published'), ('attendance_alert', 'Attendance Alert'), ('event_reminder', 'Event Reminder'), ('general_announcement', 'General Announcement'), ('academic_report', 'Academic Report'), ('fee_structure', 'Fee Structure'), ('deadline_reminder', 'Deadline Reminder'), ('behavior_alert', 'Behavior Alert')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification')),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_student_ids', models.JSONField(blank=True, default=list, help_text='List of student IDs this notification relates to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='parents.parentprofile')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_teacher_id', models.IntegerField(blank=True, help_text='Teacher ID if sent by teacher', null=True)),
                ('recipient_teacher_id', models.IntegerField(blank=True, help_text='Teacher ID if recipient is teacher', null=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('student_id', models.IntegerField(db_index=True, help_text='Student this message is about')),
                ('student_name', models.CharField(max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('requires_action', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='parents.message')),
                ('recipient_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='parents.parentprofile')),
                ('sender_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='parents.parentprofile')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(db_index=True, help_text='Student ID from students app')),
                ('student_name', models.CharField(help_text='Denormalized student name', max_length=200)),
                ('student_class', models.CharField(help_text='Current class of student', max_length=100)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Legal Guardian'), ('grandparent', 'Grandparent'), ('other', 'Other')], max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary guardian for this student')),
                ('can_view_results', models.BooleanField(default=True)),
                ('can_view_attendance', models.BooleanField(default=True)),
                ('can_view_fees', models.BooleanField(default=True)),
                ('can_make_payments', models.BooleanField(default=True)),
                ('can_communicate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='parents.parentprofile')),
            ],
            options={
                'verbose_name': 'Child Link',
                'verbose_name_plural': 'Child Links',
                'ordering': ['student_name'],
            },
        ),
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(default='fa893927761a4ea59d37537ae8cb8da1', max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='parents.parentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['guardian_id'], name='parents_par_guardia_822b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['email'], name='parents_par_email_f1d7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['phone'], name='parents_par_phone_6bf5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['access_key'], name='parents_par_access__b334c5_idx'),
        ),
        migrations.AddIndex(
            model_name='parentaccesslog',
            index=models.Index(fields=['parent', '-timestamp'], name='parents_par_parent__1749c8_idx'),
        ),
        migrations.AddIndex(
            model_name='parentaccesslog',
            index=models.Index(fields=['action'], name='parents_par_action_4edff4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['parent', '-created_at'], name='parents_not_parent__ba8265_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['parent', 'is_read'], name='parents_not_parent__cde7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='parents_not_notific_7b47cf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_parent', '-sent_at'], name='parents_mes_sender__82744e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient_parent', '-sent_at'], name='parents_mes_recipie_26a953_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['student_id'], name='parents_mes_student_21b66e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='parents_mes_is_read_0d58ed_idx'),
        ),
        migrations.AddIndex(
            model_name='childlink',
            index=models.Index(fields=['parent', 'student_id'], name='parents_chi_parent__230946_idx'),
        ),
        migrations.AddIndex(
            model_name='childlink',
            index=models.Index(fields=['student_id'], name='parents_chi_student_0234e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='childlink',
            unique_together={('parent', 'student_id')},
        ),
        migrations.AddIndex(
            model_name='portalsession',
            index=models.Index(fields=['session_key'], name='parents_por_session_3eb717_idx'),
        ),
        migrations.AddIndex(
            model_name='portalsession',
            index=models.Index(fields=['parent', '-created_at'], name='parents_por_parent__d66110_idx'),
        ),
    ]
