# Generated by Django 5.0 on 2026-03-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default='95bc98a1e87f4213a17db29d5046c2fd', help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(default='651264cb1f204b0290013199c3ad49d1', max_length=64, unique=True),
        ),
    ]
