# Generated by Django 6.0.6 on 2026-06-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default='6b9a7f723f914d54b69da2c9da1f9c56', help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(default='59cd2b6f75bc4c2f900dc43b02cb5561', max_length=64, unique=True),
        ),
    ]
