# Generated by Django 5.0 on 2026-07-21 14:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_alter_parentprofile_access_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=128)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='parent',
        ),
        migrations.AlterModelOptions(
            name='parentaccesslog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Parent Access Log', 'verbose_name_plural': 'Parent Access Logs'},
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='notification_preferences',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Denormalized recipient name', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Denormalized sender name', max_length=100),
        ),
        migrations.AddField(
            model_name='parentaccesslog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='parentaccesslog',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='parentaccesslog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parentaccesslog',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='Device fingerprint for security', max_length=128),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalsession',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='portalsession',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalsession',
            name='termination_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='childlink',
            name='relationship',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Legal Guardian'), ('grandparent', 'Grandparent'), ('other', 'Other')], default='guardian', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'Message body is required')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'Subject is required')]),
        ),
        migrations.AlterField(
            model_name='parentaccesslog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('VIEW_RESULTS', 'View Results'), ('VIEW_FEES', 'View Fees'), ('VIEW_ATTENDANCE', 'View Attendance'), ('VIEW_PROFILE', 'View Profile'), ('EDIT_PROFILE', 'Edit Profile'), ('SEND_MESSAGE', 'Send Message'), ('VIEW_MESSAGE', 'View Message'), ('PAYMENT', 'Payment'), ('DOWNLOAD_REPORT', 'Download Report'), ('SESSION_EXPIRED', 'Session Expired'), ('SESSION_TERMINATED', 'Session Terminated'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='parentaccesslog',
            name='student_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentaccesslog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default='fe8abe902f4e4a219adc7134ad2e8f7a', help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1, 'First name is required')]),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1, 'Last name is required')]),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(db_index=True, default='626feb82243a4bdaa8543e6faa315911', max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='childlink',
            index=models.Index(fields=['parent'], name='parents_chi_parent__91b79f_idx'),
        ),
        migrations.AddIndex(
            model_name='childlink',
            index=models.Index(fields=['relationship'], name='parents_chi_relatio_3edb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sent_at'], name='parents_mes_sent_at_9322f6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['student_id', '-sent_at'], name='parents_mes_student_3f6f42_idx'),
        ),
        migrations.AddIndex(
            model_name='parentaccesslog',
            index=models.Index(fields=['parent', 'action'], name='parents_par_parent__1042a6_idx'),
        ),
        migrations.AddIndex(
            model_name='parentaccesslog',
            index=models.Index(fields=['timestamp'], name='parents_par_timesta_cbd922_idx'),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['access_status'], name='parents_par_access__81a156_idx'),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['created_at'], name='parents_par_created_480c77_idx'),
        ),
        migrations.AddIndex(
            model_name='portalsession',
            index=models.Index(fields=['is_active'], name='parents_por_is_acti_e6f06a_idx'),
        ),
        migrations.AddIndex(
            model_name='portalsession',
            index=models.Index(fields=['expires_at'], name='parents_por_expires_74120f_idx'),
        ),
        migrations.AddField(
            model_name='magiclink',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='parents.parentprofile'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddIndex(
            model_name='magiclink',
            index=models.Index(fields=['token'], name='parents_mag_token_d9ad44_idx'),
        ),
        migrations.AddIndex(
            model_name='magiclink',
            index=models.Index(fields=['parent', 'expires_at'], name='parents_mag_parent__f74d53_idx'),
        ),
        migrations.AddIndex(
            model_name='magiclink',
            index=models.Index(fields=['is_used'], name='parents_mag_is_used_fca8e6_idx'),
        ),
    ]
