# Generated by Django 5.0 on 2026-03-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_alter_parentprofile_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default='ac360de135da47fb976ee9b1fa015a9c', help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(default='d24ff7f16d75450ca2c396e711ffe195', max_length=64, unique=True),
        ),
    ]
