# Generated by Django 5.0 on 2026-04-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_alter_parentprofile_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default='aa05346ca7f44013a6c762262b85d04c', help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(default='810255f4f38c42ac898f8e227612fb86', max_length=64, unique=True),
        ),
    ]
