# Generated by Django 5.0 on 2026-04-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_alter_parentprofile_access_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childlink',
            name='application_id',
            field=models.IntegerField(blank=True, help_text='Admission application ID that created this student', null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default='9b831ffd0d1a49b6a9d179e7e35538f0', help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(default='2621dd628b154a4ba393f7a35e6faa69', max_length=64, unique=True),
        ),
    ]
