# Generated by Django 5.0 on 2026-07-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_magiclink_remove_notification_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default='6baa5818f0f44b088904c24db1a0bcfc', help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(db_index=True, default='9d79ba699ee1481186192cd6a057c09d', max_length=64, unique=True),
        ),
    ]
