# Generated by Django 5.0 on 2026-04-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_alter_parentprofile_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default='967ce9892fc34661a563d8d217799ecb', help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(default='ff61af6fa8eb408bb911364894affc2d', max_length=64, unique=True),
        ),
    ]
