# Generated by Django 5.0 on 2026-07-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_alter_parentprofile_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default='240a77e96b4946fea28ae752a89c2299', help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(db_index=True, default='e708da6428714ae5a24dd3107dc8f1ce', max_length=64, unique=True),
        ),
    ]
