# Generated by Django 5.0 on 2026-04-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_childlink_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default='0d5d2ed9469e4f3c827bd1e577270797', help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(default='baaee659845a46d6bde0484352542a7f', max_length=64, unique=True),
        ),
    ]
