# Generated by Django 5.0 on 2026-04-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_alter_parentprofile_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default='e608b24a736d4335ab11a64aa27689a8', help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(default='7ed1101a523d4f1cb5a6f2e6dd1e3e09', max_length=64, unique=True),
        ),
    ]
