# Generated by Django 5.0 on 2026-07-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_alter_parentprofile_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentaccesslog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='parents.parentprofile'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default='50b21ca579ec4936a2700a6f30c77008', help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(db_index=True, default='f3fe64d74f304efb834dda7ea7bbf066', max_length=64, unique=True),
        ),
    ]
