# Generated by Django 5.0 on 2026-04-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_alter_parentprofile_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default='37107d4cace94b139f4031af36d01a32', help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(default='97c49a9ee4264bd5812357b96240a10e', max_length=64, unique=True),
        ),
    ]
