# Generated by Django 5.0 on 2026-07-22 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0006_alter_parentaccesslog_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='access_key',
            field=models.CharField(default=uuid.uuid4, help_text='Unique key for portal access URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='session_key',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
