# Generated by Django 5.0 on 2026-07-23 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0007_alter_parentprofile_access_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for email+password login (optional, magic link is primary)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+234999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
