# Generated by Django 5.0 on 2026-02-27 09:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2024/2025', max_length=50, unique=True)),
                ('code', models.CharField(help_text='e.g., 202425', max_length=20, unique=True)),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NUR1', 'Nursery 1'), ('NUR2', 'Nursery 2'), ('NUR3', 'Nursery 3'), ('PRI1', 'Primary 1'), ('PRI2', 'Primary 2'), ('PRI3', 'Primary 3'), ('PRI4', 'Primary 4'), ('PRI5', 'Primary 5'), ('PRI6', 'Primary 6'), ('JSS1', 'JSS 1'), ('JSS2', 'JSS 2'), ('JSS3', 'JSS 3'), ('SS1', 'SS 1'), ('SS2', 'SS 2'), ('SS3', 'SS 3')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('education_level', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('jss', 'Junior Secondary'), ('sss', 'Senior Secondary'), ('tertiary', 'Tertiary')], max_length=20)),
                ('max_students', models.PositiveIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1)])),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Used for ordering classes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Class',
                'verbose_name_plural': 'Student Classes',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(help_text='The academic session code (e.g., 202425)', max_length=10)),
                ('class_code', models.CharField(help_text='The standardized class code (e.g., S01)', max_length=10)),
                ('last_value', models.PositiveIntegerField(default=0, help_text='The last sequence number successfully assigned')),
            ],
            options={
                'verbose_name': 'Admission Sequence',
                'verbose_name_plural': 'Admission Sequences',
                'unique_together': {('session_code', 'class_code')},
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('TERMS_PER_SESSION', 'TERMS_PER_SESSION'), ('CURRENT_SESSION', 'CURRENT_SESSION'), ('CURRENT_TERM', 'CURRENT_TERM'), ('ADMISSIONS_OPEN', 'ADMISSIONS_OPEN'), ('ADMISSION_DEADLINE', 'ADMISSION_DEADLINE'), ('AUTO_ENROLL_APPROVED', 'AUTO_ENROLL_APPROVED'), ('INCLUDE_FEE_BALANCE_IN_REPORT', 'INCLUDE_FEE_BALANCE_IN_REPORT'), ('EXAM_CLEARANCE_REQUIRED', 'EXAM_CLEARANCE_REQUIRED'), ('RESULT_TEMPLATE', 'RESULT_TEMPLATE'), ('PASS_MARK', 'PASS_MARK'), ('DISTINCTION_MARK', 'DISTINCTION_MARK'), ('ATTENDANCE_TRACKING_ENABLED', 'ATTENDANCE_TRACKING_ENABLED'), ('MAINTENANCE_MODE', 'MAINTENANCE_MODE'), ('COMPANY_NAME', 'COMPANY_NAME'), ('COMPANY_EMAIL', 'COMPANY_EMAIL'), ('APPLICATION_FEE', 'APPLICATION_FEE'), ('ADMISSION_DEADLINE_DAYS', 'ADMISSION_DEADLINE_DAYS')], max_length=100, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Visible in public API')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 'First Term'), (2, 'Second Term'), (3, 'Third Term')])),
                ('name', models.CharField(help_text='e.g., First Term 2024/2025', max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='corecode.academicsession')),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'ordering': ['session', 'term'],
                'unique_together': {('session', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('subject_type', models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective'), ('vocational', 'Vocational')], default='core', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_nigerian_core', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_in_classes', models.ManyToManyField(blank=True, related_name='subjects', to='corecode.studentclass')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='corecode_su_code_b6c7dc_idx'), models.Index(fields=['is_active'], name='corecode_su_is_acti_39263e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('PROMOTION', 'Promotion'), ('PAYMENT', 'Payment'), ('GRADE_CHANGE', 'Grade Change'), ('WAIVER', 'Fee Waiver')], max_length=20)),
                ('app_label', models.CharField(choices=[('corecode', 'Core'), ('students', 'Students'), ('staffs', 'Staff'), ('admissions', 'Admissions'), ('finance', 'Finance'), ('results', 'Results'), ('attendance', 'Attendance')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='corecode_sy_timesta_e773ae_idx'), models.Index(fields=['app_label', 'model_name'], name='corecode_sy_app_lab_725ad8_idx'), models.Index(fields=['user', '-timestamp'], name='corecode_sy_user_id_5ddc9e_idx')],
            },
        ),
    ]
