# Generated by Django 5.0 on 2026-04-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='app_label',
            field=models.CharField(choices=[('corecode', 'Core'), ('students', 'Students'), ('staffs', 'Staff'), ('admissions', 'Admissions'), ('finance', 'Finance'), ('results', 'Results'), ('attendance', 'Attendance'), ('timetable', 'Timetable')], max_length=20),
        ),
    ]
