# Generated by Django 5.0 on 2026-04-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
