# Generated by Django 5.0 on 2026-02-27 09:34

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(help_text='Unique register identifier', max_length=50, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('session_type', models.CharField(choices=[('morning', 'Morning Session'), ('afternoon', 'Afternoon Session'), ('full_day', 'Full Day'), ('evening', 'Evening Session')], default='morning', max_length=20)),
                ('total_students', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('excused_count', models.IntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False, help_text='Register closed for further edits')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('marking_method', models.CharField(choices=[('manual', 'Manual Entry'), ('qr_code', 'QR Code Scan'), ('biometric', 'Biometric'), ('bulk_csv', 'Bulk CSV Upload'), ('api', 'API Integration')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_registers', to='corecode.academicsession')),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_registers', to='corecode.academicterm')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_registers', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_registers', to=settings.AUTH_USER_MODEL)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_registers', to='corecode.studentclass')),
            ],
            options={
                'verbose_name': 'Attendance Register',
                'verbose_name_plural': 'Attendance Registers',
                'ordering': ['-date', 'student_class', 'session_type'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(db_index=True, help_text='Student ID from students app')),
                ('student_name', models.CharField(help_text='Denormalized student name', max_length=200)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('holiday', 'Holiday'), ('sick', 'Sick')], default='present', max_length=20)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendanceregister')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['register__date', 'student_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(db_index=True, help_text='Student ID from students app')),
                ('student_name', models.CharField(max_length=200)),
                ('total_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(default=0)),
                ('excused_days', models.IntegerField(default=0)),
                ('present_percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attendance_score', models.FloatField(default=0, help_text='Weighted attendance score')),
                ('attendance_alert', models.BooleanField(default=False)),
                ('alert_reason', models.CharField(blank=True, max_length=255)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_summaries', to='corecode.academicsession')),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_summaries', to='corecode.academicterm')),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
                'ordering': ['-academic_session', '-academic_term', 'student_name'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(db_index=True, help_text='Student ID from students app', unique=True)),
                ('student_name', models.CharField(help_text='Denormalized student name', max_length=200)),
                ('code', models.CharField(help_text='Unique QR code value', max_length=100, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='attendance/qrcodes/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'indexes': [models.Index(fields=['code'], name='attendance__code_39f696_idx'), models.Index(fields=['student_id'], name='attendance__student_153105_idx'), models.Index(fields=['is_active'], name='attendance__is_acti_3b7fa6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='attendanceregister',
            index=models.Index(fields=['student_class', 'date'], name='attendance__student_4a1325_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceregister',
            index=models.Index(fields=['academic_session', 'academic_term'], name='attendance__academi_051916_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceregister',
            index=models.Index(fields=['register_number'], name='attendance__registe_4daf5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceregister',
            unique_together={('student_class', 'date', 'session_type')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student_id'], name='attendance__student_bf8a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='attendance__status_741eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['register', 'student_id'], name='attendance__registe_e536d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('register', 'student_id')},
        ),
        migrations.AddIndex(
            model_name='attendancesummary',
            index=models.Index(fields=['student_id'], name='attendance__student_ac63a5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummary',
            index=models.Index(fields=['attendance_alert'], name='attendance__attenda_24ca19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('student_id', 'academic_session', 'academic_term')},
        ),
    ]
