# Generated by Django 5.0 on 2026-03-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='request_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
