# Generated by Django 5.0 on 2026-04-15 13:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(help_text='Unique application reference (e.g., APP-2024-0001)', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('nationality', models.CharField(default='Nigerian', max_length=50)),
                ('application_type', models.CharField(choices=[('new', 'New Student'), ('transfer', 'Transfer from Another School'), ('re_admission', 'Re-admission')], default='new', max_length=20)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_class', models.CharField(blank=True, max_length=50)),
                ('guardian_first_name', models.CharField(max_length=50)),
                ('guardian_last_name', models.CharField(max_length=50)),
                ('guardian_relationship', models.CharField(max_length=50)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_address', models.TextField(blank=True)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('invoice_id', models.IntegerField(blank=True, help_text='ID of created invoice from apps.finance app', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('enrolled_student_id', models.IntegerField(blank=True, help_text='ID of created student record (from students app)', null=True)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_staff_child', models.BooleanField(default=False, help_text="Whether this application is for a staff member's child")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applying_for_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='corecode.studentclass')),
                ('applying_for_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='corecode.academicsession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport Photograph'), ('birth_certificate', 'Birth Certificate'), ('transfer_certificate', 'Transfer Certificate'), ('report_card', 'Previous Report Card'), ('medical_record', 'Medical Record'), ('other', 'Other Document')], max_length=20)),
                ('file', models.FileField(upload_to='applications/documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'ordering': ['document_type', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='admissions.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Note',
                'verbose_name_plural': 'Application Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='admissions.application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Review',
                'verbose_name_plural': 'Application Reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionsPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Early Admission', 'Regular Admission'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for open-ended', null=True)),
                ('application_fee', models.DecimalField(decimal_places=2, default=5000, help_text='Application fee for this period (can differ by period)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='If active, applications can be submitted during this period')),
                ('max_applications', models.PositiveIntegerField(blank=True, help_text='Maximum applications allowed for this period (leave blank for unlimited)', null=True)),
                ('current_applications', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_periods', to='corecode.academicsession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admission_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admissions Period',
                'verbose_name_plural': 'Admissions Periods',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['academic_session', 'is_active'], name='admissions__academi_d31fb2_idx'), models.Index(fields=['start_date', 'end_date'], name='admissions__start_d_4f6ad2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_number'], name='admissions__applica_7574f8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='admissions__status_cd8e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['email'], name='admissions__email_0a54ef_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['invoice_id'], name='admissions__invoice_9d649a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-created_at'], name='admissions__created_dbbfa0_idx'),
        ),
    ]
