# Generated by Django 5.0 on 2026-03-30 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('corecode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationpayment',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationpayment',
            name='created_by',
        ),
        migrations.AddField(
            model_name='application',
            name='invoice_id',
            field=models.IntegerField(blank=True, help_text='ID of created invoice from apps.finance app', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['invoice_id'], name='admissions__invoice_9d649a_idx'),
        ),
        migrations.DeleteModel(
            name='ApplicationPayment',
        ),
    ]
