# Generated by Django 5.0 on 2026-04-01 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_remove_applicationpayment_application_and_more'),
        ('corecode', '0002_allow_null_log_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Early Admission', 'Regular Admission'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for open-ended', null=True)),
                ('application_fee', models.DecimalField(decimal_places=2, default=5000, help_text='Application fee for this period (can differ by period)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='If active, applications can be submitted during this period')),
                ('max_applications', models.PositiveIntegerField(blank=True, help_text='Maximum applications allowed for this period (leave blank for unlimited)', null=True)),
                ('current_applications', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_periods', to='corecode.academicsession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admission_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admissions Period',
                'verbose_name_plural': 'Admissions Periods',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['academic_session', 'is_active'], name='admissions__academi_d31fb2_idx'), models.Index(fields=['start_date', 'end_date'], name='admissions__start_d_4f6ad2_idx')],
            },
        ),
    ]
