# Generated by Django 5.0 on 2026-04-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admissionsperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_staff_child',
            field=models.BooleanField(default=False, help_text="Whether this application is for a staff member's child"),
        ),
    ]
