# Generated by Django 5.0 on 2026-04-15 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('result_published', 'Results Published'), ('report_card_ready', 'Report Card Ready'), ('term_begins', 'Term Begins'), ('term_ends', 'Term Ends'), ('payment_receipt', 'Payment Receipt'), ('payment_reminder', 'Payment Reminder'), ('invoice_generated', 'Invoice Generated'), ('waiver_approved', 'Waiver Approved'), ('attendance_alert', 'Attendance Alert'), ('low_attendance', 'Low Attendance Warning'), ('application_status', 'Application Status Update'), ('admission_offer', 'Admission Offer'), ('event_reminder', 'Event Reminder'), ('general_announcement', 'General Announcement'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('performance_review', 'Performance Review')], max_length=50)),
                ('email_subject', models.CharField(blank=True, max_length=200)),
                ('email_template', models.TextField(help_text='HTML email template with variables')),
                ('sms_template', models.CharField(blank=True, help_text='SMS template (max 160 chars)', max_length=160)),
                ('push_title', models.CharField(blank=True, max_length=100)),
                ('push_body', models.CharField(blank=True, max_length=200)),
                ('in_app_message', models.TextField(blank=True)),
                ('available_variables', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('result_published', 'Results Published'), ('report_card_ready', 'Report Card Ready'), ('term_begins', 'Term Begins'), ('term_ends', 'Term Ends'), ('payment_receipt', 'Payment Receipt'), ('payment_reminder', 'Payment Reminder'), ('invoice_generated', 'Invoice Generated'), ('waiver_approved', 'Waiver Approved'), ('attendance_alert', 'Attendance Alert'), ('low_attendance', 'Low Attendance Warning'), ('application_status', 'Application Status Update'), ('admission_offer', 'Admission Offer'), ('event_reminder', 'Event Reminder'), ('general_announcement', 'General Announcement'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('performance_review', 'Performance Review')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('action_text', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('channels', models.JSONField(default=list, help_text='List of channels to use')),
                ('recipient_type', models.CharField(choices=[('student', 'Single Student'), ('parent', 'Single Parent'), ('staff', 'Single Staff'), ('all_students', 'All Students'), ('all_parents', 'All Parents'), ('all_staff', 'All Staff'), ('specific_class', 'Specific Class'), ('specific_role', 'Specific Role')], max_length=20)),
                ('recipient_id', models.IntegerField(blank=True, null=True)),
                ('recipient_group', models.CharField(blank=True, max_length=100)),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], max_length=20)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(default=dict, help_text='Format: {notification_type: [channels]}')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_id'], name='notificatio_notific_aa9b90_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_type', 'recipient_id'], name='notificatio_recipie_e8689e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='notificatio_status_d92267_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx'),
        ),
    ]
