# Generated by Django 5.0 on 2026-07-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_group',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
